name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4.2
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2 # checks out the code from the repository
      - name: Set up Java 11 # sets up Java 11 on the runner
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: Build project # builds the project with Maven and skips the tests
        run: mvn clean install -DskipTests=true
      - name: Run integration tests # runs the integration tests with Maven
        run: mvn test -Dtest=com.springboot.eventservice.EventServiceApplicationTests
        env:
          SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/event-service # sets the MongoDB URI for the tests to use
